# Basic appearance
gappih=2
gappiv=2
gappoh=2
gappov=2
borderpx=5
rootcolor=0x090a0bff
bordercolor=0x76858eff
focuscolor=0x2846AAff
urgentcolor=0x5B626Bff
globalcolor=0x2846AAff
scratchpadcolor=0x090a0bff
overlaycolor=0xa9becbff
dropcolor=0x2846AA55
splitcolor=0x5B626Bff
maximizescreencolor=0xa9becbff
focused_opacity=1.0
unfocused_opacity=1.0
border_radius=0
no_radius_when_single=1
shadows=0
layer_shadows=0
blur=0
blur_layer=0
no_border_when_single=1