# Session startup
exec-once=bash ~/.config/mango/scripts/mangoWalColors
exec-once=waybar -c ~/.config/mango/config.jsonc -s ~/.config/mango/style.css
exec-once=flameshot
exec-once=blueman-applet
exec-once=bash ~/.config/mango/scripts/battery-notify