# Session startup (deps: ./install.sh)
exec-once=swaync
exec-once=blueman-applet
exec-once=nm-applet
exec-once=bash ~/.config/mango/scripts/battery-notify
exec-once=awww-daemon
exec-once=bash ~/.config/mango/scripts/wallpaperChangeWayland
exec-once=bash ~/.config/mango/scripts/reloadWaybar --with-colors
