# Session startup (deps: ./install.sh)
exec-once=swaync
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=blueman-applet
exec-once=nm-applet
exec-once=bash ~/.config/mango/scripts/battery-notify
exec-once=awww-daemon
exec-once=bash ~/.config/mango/scripts/wallpaperChangeWayland
exec-once=bash ~/.config/mango/scripts/reloadWaybar --with-colors
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_SESSION_ID XDG_SESSION_TYPE XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE SWAYSOCK NIRI_SOCKET
exec-once=systemctl --user restart veilad.service veila-idle.service
exec-once=wayland-pipewire-idle-inhibit --wayland
