#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers"

CURRENT_WALLPAPER=$(cat ~/.cache/wal/wal)

# Find all images, shuffle the list (null-safe)
mapfile -d '' wallpapers < <(find -L "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | shuf -z)

# Format input for Rofi: wallpaper path as text, wallpaper image as icon
input=""
for wallpaper in "${wallpapers[@]}"; do
    input+="${wallpaper}\0icon\x1f${wallpaper}\n"
done

# Show menu with preview theme
WALLPAPER=$(echo -e "$input" | rofi -dmenu -show-icons -theme ~/.config/mango/rofi/themes/wallpaper-preview.rasi -p "󰉏 Wallpapers")

# Exit if no selection
[[ -z "$WALLPAPER" ]] && exit 0

if [ "$CURRENT_WALLPAPER" != "$WALLPAPER" ]; then
    awww img "$WALLPAPER" --transition-type any --transition-step 255 --transition-fps 144 >/dev/null 2>&1
    sleep 1
    wal -i "$WALLPAPER" >/dev/null 2>&1
    bash ~/.config/mango/scripts/mangoWalColors &>/dev/null || true
    if ! pgrep -x waybar >/dev/null; then
        bash ~/.config/mango/scripts/reloadWaybar &>/dev/null || true
    fi
#    killall pasystray; pasystray & > /dev/null 2>&1
#    killall blueman-applet; blueman-applet & > /dev/null 2>&1
#    killall battery-notify; bash ~/.config/mango/scripts/battery-notify & > /dev/null 2>&1
#    killall nm-applet; nm-applet --indicator & > /dev/null 2>&1
#    notify-send "Wallpaper Changed" --icon="$WALLPAPER"
fi
