#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/.local/wallpapers"

CURRENT_WALLPAPER=$(cat ~/.cache/wal/wal)

# Find all images, shuffle the list (null-safe)
mapfile -d '' wallpapers < <(find -L "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | shuf -z)

# Format input for Rofi: wallpaper path as text, wallpaper image as icon
input=""
for wallpaper in "${wallpapers[@]}"; do
    input+="${wallpaper}\0icon\x1f${wallpaper}\n"
done

# Show menu with preview theme
WALLPAPER=$(echo -e "$input" | rofi -dmenu -show-icons -theme ~/.config/rofi/themes/wallpaper-preview.rasi -p "󰉏 Wallpapers")

# Exit if no selection
[[ -z "$WALLPAPER" ]] && exit 0

if [ "$CURRENT_WALLPAPER" != "$WALLPAPER" ]; then
    wal -i "$WALLPAPER" & > /dev/null 2>&1
    bash ~/.config/mango/scripts/mangoWalColors &>/dev/null || true
    killall -SIGUSR2 waybar 2>/dev/null || true
    killall pasystray; pasystray & > /dev/null 2>&1
    killall blueman-applet; blueman-applet & > /dev/null 2>&1
    killall battery-notify; bash ~/.config/mango/scripts/battery-notify & > /dev/null 2>&1
    killall flameshot; flameshot & > /dev/null 2>&1
    killall nm-applet; nm-applet --indicator & > /dev/null 2>&1
    swaybg -i "$WALLPAPER" & > /dev/null 2>&1
    notify-send "Wallpaper Changed" --icon="$WALLPAPER"
fi

