#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers"
CURRENT_WALLPAPER=$(cat ~/.cache/wal/wal)

while true
do
    WALLPAPER=$(find -L "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | shuf -n 1)
    if [ "$CURRENT_WALLPAPER" != "$WALLPAPER" ]
    then
        awww img "$WALLPAPER" --transition-type any --transition-step 255 --transition-fps 144 >/dev/null 2>&1
        sleep 1
        wal -i "$WALLPAPER" >/dev/null 2>&1
        bash ~/.config/mango/scripts/mangoWalColors &>/dev/null || true
        if ! pgrep -x waybar >/dev/null; then
            bash ~/.config/mango/scripts/reloadWaybar &>/dev/null || true
        fi
       # killall pasystray; pasystray & > /dev/null 2>&1
       # killall blueman-applet; blueman-applet & > /dev/null 2>&1
       # killall battery-notify; bash ~/.config/mango/scripts/battery-notify & > /dev/null 2>&1
       # killall nm-applet; nm-applet --indicator & > /dev/null 2>&1
       #notify-send "Wallpaper Changed" --icon="$WALLPAPER"
        exit
    fi
done

